<a href="https://colab.research.google.com/github/fancifulghost/Lorna/blob/main/Encode_Gender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
import json

def get_data():
  url="https://qqlwlo6mlj.execute-api.eu-west-2.amazonaws.com/test/listening_data"
  query_data = {
      "query":"read_responders",
      "returnfields":[],
      "variables":{}
  }
  data = requests.post(url, data=json.dumps(query_data)).json()
  if 'success' in data.keys():
    return pd.json_normalize(data['success'])#
  else:
    return None

df = get_data()
if df is not None:

# Python function ( to be applied to the dataframe gender column and should take the dataframe, the column and a keyword as parameters)
# - Creates a new column called gender-encoded
# - Applies a function across the gender column that will replace all items that are not 'Male', 'Female' or 'Prefer not to say', with Other.
# - Returns the resulting dataframe


  def encode_gender(df, **kwds):

      key = kwds['key']

      if df[key] == "Female" or "Male" or "Prefer not to say":
        return df[key] 
      else:
        return "Other"

  df["gender-encoded"] = df.apply(encode_gender, axis=1, key="gender")
display(df)

None

In [ ]:
import pandas as pd
url = "https://drive.google.com/uc?export=download&id=144dlnCJ7rHs4LllVqXtsg2ABpnN_XucB"
df = pd.read_csv(url)

df = df[['Where are you based?','Which age range are you in?', 'How would you describe your gender?', 'Are you living with a disability or a long-term condition? If so how would you describe this?']]

def encode_gender(df, **kwds):

      key = kwds['key']

      if df[key] == "Female":
        return df[key]
      if df[key] == "Male":
        return df[key]
      if df[key] == "Prefer not to say":
        return df[key]
      else:
        return "Other"


df["gender-encoded"] = df.apply(encode_gender, axis=1, key="How would you describe your gender?")
df

#Testing the count:

# def test_count_gender():
#   print(df['gender-encoded'].value_counts())
# test_count_gender()

,Where are you based?,Which age range are you in?,How would you describe your gender?,Are you living with a disability or a long-term condition? If so how would you describe this?,gender-encoded
0,Medway,70-79,Male,After affects of cancer,Male
1,Medway,60-69,Male,Mental health condition - depression.,Male
2,Medway,60-69,Male,"Alcohol dependent, stoma bag.",Male
3,Medway,70-79,Female,"COPD, mental health condition - depression.",Female
4,Medway,40-49,Female,Yes but not want to give any info.,Female
...,...,...,...,...,...
174,Medway,50-59,Male,No,Male
175,Medway,60-69,Male,No,Male
176,Medway,60-69,Female,No,Female
177,Medway,70-79,Female,No,Female
178,Medway,70-79,Female,No,Female